CREATE TABLE customer
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "customer id"           VARCHAR(255),
    "customer name"         VARCHAR(255),
    "customer phone number" INTEGER,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE discounted_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "item code"       VARCHAR(255),
    "item name"       VARCHAR(255),
    "normal price"    DOUBLE PRECISION,
    discount          DOUBLE PRECISION,
    "discount price"  DOUBLE PRECISION,
    "expiration date" INTEGER,
    quantity          INTEGER,
    CONSTRAINT pk_discounteditems PRIMARY KEY (id)
);

CREATE TABLE items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "item code"       VARCHAR(255),
    "item name"       VARCHAR(255),
    price             DOUBLE PRECISION,
    "expiration date" INTEGER,
    quantity          INTEGER,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE items_quantity
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "item code"          VARCHAR(255),
    "item name"          VARCHAR(255),
    "input quantity"     INTEGER,
    "sold quantity"      INTEGER,
    "now stock quantity" INTEGER,
    CONSTRAINT pk_itemsquantity PRIMARY KEY (id)
);

CREATE TABLE profit_loss_data
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "item code"                VARCHAR(255),
    "item name"                VARCHAR(255),
    "input item quantity"      INTEGER,
    "1 item price put in shop" DOUBLE PRECISION,
    "1 item selling price"     DOUBLE PRECISION,
    "sold item quantity"       INTEGER,
    period VARCHAR (255),
    "profit or loss in rupees" DOUBLE PRECISION,
    CONSTRAINT pk_profitlossdata PRIMARY KEY (id)
);

CREATE TABLE shoplifter
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "shoplifter id"           VARCHAR(255),
    "shoplifter name"         VARCHAR(255),
    "shoplifter phone number" INTEGER,
    "delivery item"           VARCHAR(255),
    CONSTRAINT pk_shoplifter PRIMARY KEY (id)
);

CREATE TABLE weighing_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "item code"       VARCHAR(255),
    "item name"       VARCHAR(255),
    weight            VARCHAR(255),
    "1kg price"       DOUBLE PRECISION,
    "expiration date" INTEGER,
    CONSTRAINT pk_weighingitems PRIMARY KEY (id)
);